** DONE Add a bash script to run the program
** DONE Add a readme on how to run the program
** DONE Move the classes in the correct packages
** TODO Do a simple load test
** TODO Add documentation for each method as required
** TODO Add more unit tests
** TODO Look at total drinks instead of finished drinks
** Think of the case when there are only two players and one maxDrinks drink, if anyone of them roles a winner then the simulator should wait for the other person to stop drinking and then declare the winner
** No player should drink more than the maximum number of drinks. If he is drinking the last one he should be allowed to finish.
** deepak says: 'I've had too many.  I need to stop.' This messaging should not appear immediately after the person is asked to drink. it should appear only after he person has finished drinking his last drinking
                                       System.out.println(new StringBuffer(player.getName()).append(" says: 'I've had too many.  I need to stop.'").toString());
** Remove the Illegal State Exception. Run a full test of the system. Improve Java documentation